### ISSUE TITLE
本地sdk 运行失败：Error: ERR_INIT_SDK_LOST_CONFIG     at init (./server/node_modules/wafer-node-sdk/index.js:48:190)

### ISSUE THREAD

**Issue by ahuigo** [tencentyun/wafer2-quickstart#11]
```
$ node install
$ node app.js
if ([rootPathname, useQcloudLogin, cos, serverHost, tunnelServerUrl, tunnelSignatureKey, qcloudAppId, qcloudSecretId, qcloudSecretKey, wxMessageToken].some(v => v === undefined)) throw new Error(ERRORS.ERR_INIT_SDK_LOST_CONFIG)
                                                                                                                                                                                       ^

Error: ERR_INIT_SDK_LOST_CONFIG
    at init (..../server/node_modules/wafer-node-sdk/index.js:48:190)
    at Object.<anonymous> (.../server/qcloud.js:36:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)

```

本地sdk 运行时，和腾讯node 运行时难道不一样吗？

**Comment by jas0ncn** [comment]
https://cloud.tencent.com/document/product/619/11445
不一样。Wafer 方案环境中内置了配置，参考这里补齐配置。
